--AMIDEV_IM
--AMIDEV_ADHOC

SELECT file_id, name as [logical_file_name], physical_name
FROM sys.database_files

USE [master];
GO

--Disconnect all existing session.
ALTER DATABASE AMIDEV_ADHOC SET SINGLE_USER WITH ROLLBACK IMMEDIATE
GO
--Change database in to OFFLINE mode.
ALTER DATABASE AMIDEV_ADHOC SET OFFLINE

--rename files

ALTER DATABASE AMIDEV_ADHOC MODIFY FILE (Name='AMIDEV_ADHOC', FILENAME='F:\MSSQL\Data\AMIDEV_ADHOC_Data.mdf')
GO

ALTER DATABASE AMIDEV_ADHOC SET ONLINE
Go
ALTER DATABASE AMIDEV_ADHOC SET MULTI_USER
Go