USE [TPS_DBA]
GO

/****** Object:  StoredProcedure [dbo].[uspRenameDevDBFiles]    Script Date: 4/10/2020 1:29:41 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

IF OBJECT_ID('uspRenameDevDBFiles','P') IS NOT NULL DROP PROCEDURE [dbo].[uspRenameDevDBFiles]
GO


CREATE PROCEDURE [dbo].[uspRenameDevDBFiles] 

--EXEC uspRenameDevDBFiles 

--You must rename the actual files after running this on F and E drives

AS

SET NOCOUNT ON

DECLARE @SQL VARCHAR(8000)
DECLARE @Customer VARCHAR(255)

SET @Customer=(select [dbo].[udfGetServerSetting]('SQLServerAgentOperator'))

SET @SQL='
--Disconnect all existing session
USE MASTER ALTER DATABASE '+@Customer+' SET SINGLE_USER WITH ROLLBACK IMMEDIATE
USE MASTER ALTER DATABASE '+@Customer+'_Zubr_IM SET SINGLE_USER WITH ROLLBACK IMMEDIATE
USE MASTER ALTER DATABASE '+@Customer+'_ADHOC SET SINGLE_USER WITH ROLLBACK IMMEDIATE
USE MASTER ALTER DATABASE '+@Customer+'_CM SET SINGLE_USER WITH ROLLBACK IMMEDIATE
USE MASTER ALTER DATABASE '+@Customer+'_TSK SET SINGLE_USER WITH ROLLBACK IMMEDIATE
USE MASTER ALTER DATABASE '+@Customer+'_TSK_ADHOC SET SINGLE_USER WITH ROLLBACK IMMEDIATE
USE MASTER ALTER DATABASE '+@Customer+'_TSK_IM SET SINGLE_USER WITH ROLLBACK IMMEDIATE
USE MASTER ALTER DATABASE '+@Customer+'_TSK_RPT SET SINGLE_USER WITH ROLLBACK IMMEDIATE

--Change database in to OFFLINE mode.
USE MASTER ALTER DATABASE '+@Customer+' SET OFFLINE
USE MASTER ALTER DATABASE '+@Customer+'_Zubr_IM SET OFFLINE
USE MASTER ALTER DATABASE '+@Customer+'_ADHOC SET OFFLINE
USE MASTER ALTER DATABASE '+@Customer+'_CM SET OFFLINE
USE MASTER ALTER DATABASE '+@Customer+'_TSK SET OFFLINE
USE MASTER ALTER DATABASE '+@Customer+'_TSK_ADHOC SET OFFLINE
USE MASTER ALTER DATABASE '+@Customer+'_TSK_IM SET OFFLINE
USE MASTER ALTER DATABASE '+@Customer+'_TSK_RPT SET OFFLINE

--Rename files
USE MASTER ALTER DATABASE '+@Customer+' MODIFY FILE (Name=''AMIDEV'', FILENAME=''F:\MSSQL\DATA\'+@Customer+'_Data.mdf'')
USE MASTER ALTER DATABASE '+@Customer+' MODIFY FILE (Name=''AMIDEV_LOG'', FILENAME=''E:\MSSQL\LOG\'+@Customer+'_Log.ldf'')

USE MASTER ALTER DATABASE '+@Customer+'_Zubr_IM MODIFY FILE (Name=''AMIDEV__Zubr_IM'', FILENAME=''F:\MSSQL\DATA\'+@Customer+'_Zubr_IM_Data.mdf'')
USE MASTER ALTER DATABASE '+@Customer+'_Zubr_IM MODIFY FILE (Name=''AMIDEV_Zubr_IM_LOG'', FILENAME=''E:\MSSQL\LOG\'+@Customer+'_Zubr_IM_Log.ldf'')

USE MASTER ALTER DATABASE '+@Customer+'_ADHOC MODIFY FILE (Name=''AMIDEV_ADHOC'', FILENAME=''F:\MSSQL\DATA\'+@Customer+'_ADHOC_Data.mdf'')
USE MASTER ALTER DATABASE '+@Customer+'_ADHOC MODIFY FILE (Name=''AMIDEV_ADHOC_LOG'', FILENAME=''E:\MSSQL\LOG\'+@Customer+'_ADHOC_Log.ldf'')

USE MASTER ALTER DATABASE '+@Customer+'_CM MODIFY FILE (Name=''AMIDEV_CM'', FILENAME=''F:\MSSQL\DATA\'+@Customer+'_CM_Data.mdf'')
USE MASTER ALTER DATABASE '+@Customer+'_CM MODIFY FILE (Name=''AMIDEV_CM_LOG'', FILENAME=''E:\MSSQL\LOG\'+@Customer+'_CM_Log.ldf'')

USE MASTER ALTER DATABASE '+@Customer+'_TSK MODIFY FILE (Name=''AMIDEV_TSK'', FILENAME=''F:\MSSQL\DATA\'+@Customer+'_TSK_Data.mdf'')
USE MASTER ALTER DATABASE '+@Customer+'_TSK MODIFY FILE (Name=''AMIDEV_TSK_LOG'', FILENAME=''E:\MSSQL\LOG\'+@Customer+'_TSK_Log.ldf'')

USE MASTER ALTER DATABASE '+@Customer+'_TSK_ADHOC MODIFY FILE (Name=''AMIDEV_TSK_ADHOC'', FILENAME=''F:\MSSQL\DATA\'+@Customer+'_TSK_ADHOC_Data.mdf'')
USE MASTER ALTER DATABASE '+@Customer+'_TSK_ADHOC MODIFY FILE (Name=''AMIDEV_TSK_ADHOC_LOG'', FILENAME=''E:\MSSQL\LOG\'+@Customer+'_TSK_ADHOC_Log.ldf'')

USE MASTER ALTER DATABASE '+@Customer+'_TSK_IM MODIFY FILE (Name=''AMIDEV_TSK_IM'', FILENAME=''F:\MSSQL\DATA\'+@Customer+'_TSK_IM_Data.mdf'')
USE MASTER ALTER DATABASE '+@Customer+'_TSK_IM MODIFY FILE (Name=''AMIDEV_TSK_IM_LOG'', FILENAME=''E:\MSSQL\LOG\'+@Customer+'_TSK_IM_Log.ldf'')

USE MASTER ALTER DATABASE '+@Customer+'_TSK_RPT MODIFY FILE (Name=''AMIDEV_TSK_RPT'', FILENAME=''F:\MSSQL\DATA\'+@Customer+'_TSK_RPT_Data.mdf'')
USE MASTER ALTER DATABASE '+@Customer+'_TSK_RPT MODIFY FILE (Name=''AMIDEV_TSK_RPT_LOG'', FILENAME=''E:\MSSQL\LOG\'+@Customer+'_TSK_RPT_Log.ldf'')


'
--PRINT @SQL
EXEC(@SQL)
GO


