USE [TPS_DBA]
GO

IF OBJECT_ID('uspRenameDBFiles','P') IS NOT NULL DROP PROCEDURE [dbo].uspRenameDBFiles
GO


/****** Object:  StoredProcedure [dbo].[uspRenameDBFiles]    Script Date: 4/10/2020 11:38:58 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE PROCEDURE [dbo].[uspRenameDBFiles] 

--EXEC uspRenameDevDBFiles 

--You must rename the actual files after running this on F and E drives

AS

SET NOCOUNT ON

DECLARE @SQL VARCHAR(8000)
DECLARE @Customer VARCHAR(255)

SET @Customer=(select [dbo].[udfGetServerSetting]('SQLServerAgentOperator'))

SET @SQL='
--Disconnect all existing session
USE MASTER ALTER DATABASE '+@Customer+'_ADHOC SET SINGLE_USER WITH ROLLBACK IMMEDIATE
USE MASTER ALTER DATABASE '+@Customer+'_TSK SET SINGLE_USER WITH ROLLBACK IMMEDIATE
USE MASTER ALTER DATABASE '+@Customer+'_TSK_ADHOC SET SINGLE_USER WITH ROLLBACK IMMEDIATE
USE MASTER ALTER DATABASE '+@Customer+'_TSK_IM SET SINGLE_USER WITH ROLLBACK IMMEDIATE
USE MASTER ALTER DATABASE '+@Customer+'_TSK_RPT SET SINGLE_USER WITH ROLLBACK IMMEDIATE

--Change database in to OFFLINE mode.
USE MASTER ALTER DATABASE '+@Customer+'_ADHOC SET OFFLINE
USE MASTER ALTER DATABASE '+@Customer+'_TSK SET OFFLINE
USE MASTER ALTER DATABASE '+@Customer+'_TSK_ADHOC SET OFFLINE
USE MASTER ALTER DATABASE '+@Customer+'_TSK_IM SET OFFLINE
USE MASTER ALTER DATABASE '+@Customer+'_TSK_RPT SET OFFLINE

--Rename files
USE MASTER ALTER DATABASE '+@Customer+'_ADHOC MODIFY FILE (Name=''AMI_ADHOC'', FILENAME=''F:\MSSQL\DATA\'+@Customer+'_ADHOC_Data.mdf'')
USE MASTER ALTER DATABASE '+@Customer+'_ADHOC MODIFY FILE (Name=''AMI_ADHOC_LOG'', FILENAME=''E:\MSSQL\LOG\'+@Customer+'_ADHOC_Log.ldf'')

USE MASTER ALTER DATABASE '+@Customer+'_TSK MODIFY FILE (Name=''AMI_TSK'', FILENAME=''F:\MSSQL\DATA\'+@Customer+'_TSK_Data.mdf'')
USE MASTER ALTER DATABASE '+@Customer+'_TSK MODIFY FILE (Name=''AMI_TSK_LOG'', FILENAME=''E:\MSSQL\LOG\'+@Customer+'_TSK_Log.ldf'')

USE MASTER ALTER DATABASE '+@Customer+'_TSK_ADHOC MODIFY FILE (Name=''AMI_TSK_ADHOC'', FILENAME=''F:\MSSQL\DATA\'+@Customer+'_TSK_ADHOC_Data.mdf'')
USE MASTER ALTER DATABASE '+@Customer+'_TSK_ADHOC MODIFY FILE (Name=''AMI_TSK_ADHOC_LOG'', FILENAME=''E:\MSSQL\LOG\'+@Customer+'_TSK_ADHOC_Log.ldf'')

USE MASTER ALTER DATABASE '+@Customer+'_TSK_IM MODIFY FILE (Name=''AMI_TSK_IM'', FILENAME=''F:\MSSQL\DATA\'+@Customer+'_TSK_IM_Data.mdf'')
USE MASTER ALTER DATABASE '+@Customer+'_TSK_IM MODIFY FILE (Name=''AMI_TSK_IM_LOG'', FILENAME=''E:\MSSQL\LOG\'+@Customer+'_TSK_IM_Log.ldf'')

USE MASTER ALTER DATABASE '+@Customer+'_TSK_RPT MODIFY FILE (Name=''AMI_TSK_RPT'', FILENAME=''F:\MSSQL\DATA\'+@Customer+'_TSK_RPT_Data.mdf'')
USE MASTER ALTER DATABASE '+@Customer+'_TSK_RPT MODIFY FILE (Name=''AMI_TSK_RPT_LOG'', FILENAME=''E:\MSSQL\LOG\'+@Customer+'_TSK_RPT_Log.ldf'')


'
--PRINT @SQL
EXEC(@SQL)
GO


