USE [TPS_DBA]
GO

IF OBJECT_ID('uspRenameDBServerOnline','P') IS NOT NULL DROP PROCEDURE [dbo].[uspRenameDBServerOnline]
GO


/****** Object:  StoredProcedure [dbo].[uspRenameDBServerOnline]    Script Date: 4/10/2020 11:39:57 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



CREATE PROCEDURE [dbo].[uspRenameDBServerOnline] 

--EXEC uspRenameDevDBServerOnline 

AS

SET NOCOUNT ON

DECLARE @SQL VARCHAR(8000)
DECLARE @Customer VARCHAR(255)

SET @Customer=(select [dbo].[udfGetServerSetting]('SQLServerAgentOperator'))

SET @SQL='
USE MASTER ALTER DATABASE '+@Customer+'_ADHOC SET ONLINE
USE MASTER ALTER DATABASE '+@Customer+'_ADHOC SET MULTI_USER

USE MASTER ALTER DATABASE '+@Customer+'_TSK SET ONLINE
USE MASTER ALTER DATABASE '+@Customer+'_TSK SET MULTI_USER

USE MASTER ALTER DATABASE '+@Customer+'_TSK_ADHOC SET ONLINE
USE MASTER ALTER DATABASE '+@Customer+'_TSK_ADHOC SET MULTI_USER

USE MASTER ALTER DATABASE '+@Customer+'_TSK_IM SET ONLINE
USE MASTER ALTER DATABASE '+@Customer+'_TSK_IM SET MULTI_USER

USE MASTER ALTER DATABASE '+@Customer+'_TSK_RPT SET ONLINE
USE MASTER ALTER DATABASE '+@Customer+'_TSK_RPT SET MULTI_USER

'
--PRINT @SQL
EXEC(@SQL)
GO


